--ALEATORIZANDO IDS P/ CLIENTES, VENDEDORES E PAGAMENTO
SELECT TOP 1 IDCLIENTE FROM CLIENTE
ORDER BY NEWID()
GO

SELECT TOP 1 IDVENDEDOR FROM VENDEDOR
ORDER BY NEWID()
GO

SELECT TOP 1 IDFORMA FROM FORMA_PAGAMENTO
ORDER BY NEWID()
GO

-- ALEATORIZANDO A DATA
SELECT RAND() * 12 --MÊS
SELECT RAND() * 31 --DIA

--PREENCHENDO A TABELA NOTAS FISCAIS REFERENTE A 2015
DECLARE
	@ID_CLIENTE INT,
	@ID_VENDEDOR INT,	
	@ID_FORMA_PAGAMENTO INT,
	@DATA DATE
BEGIN
	SET @ID_CLIENTE = (SELECT TOP 1 IDCLIENTE FROM CLIENTE ORDER BY NEWID())

	SET @ID_VENDEDOR = (SELECT TOP 1 IDVENDEDOR FROM VENDEDOR ORDER BY NEWID())

	SET @ID_FORMA_PAGAMENTO = (SELECT TOP 1 IDFORMA FROM FORMA_PAGAMENTO ORDER BY NEWID())

	SET @DATA = (SELECT
				CONVERT(DATE, CONVERT(VARCHAR(15),'2015-' + 
				CONVERT(VARCHAR(5), (CONVERT(INT, RAND() * 12)) + 1) + '-' + 
				CONVERT(VARCHAR(5), (CONVERT(INT, RAND() * 27)) + 1))))

	INSERT INTO NOTA_FISCAL (ID_CLIENTE, ID_VENDEDOR, ID_FORMA, DATA) VALUES 
	(@ID_CLIENTE, @ID_VENDEDOR, @ID_FORMA_PAGAMENTO, @DATA)

END
GO 8000


--PREENCHENDO A TABELA NOTAS FISCAIS REFERENTE A 2016
DECLARE
	@ID_CLIENTE INT,
	@ID_VENDEDOR INT,	
	@ID_FORMA_PAGAMENTO INT,
	@DATA DATE
BEGIN
	SET @ID_CLIENTE = (SELECT TOP 1 IDCLIENTE FROM CLIENTE ORDER BY NEWID())

	SET @ID_VENDEDOR = (SELECT TOP 1 IDVENDEDOR FROM VENDEDOR ORDER BY NEWID())

	SET @ID_FORMA_PAGAMENTO = (SELECT TOP 1 IDFORMA FROM FORMA_PAGAMENTO ORDER BY NEWID())

	SET @DATA = (SELECT
				CONVERT(DATE, CONVERT(VARCHAR(15),'2016-' + 
				CONVERT(VARCHAR(5), (CONVERT(INT, RAND() * 12)) + 1) + '-' + 
				CONVERT(VARCHAR(5), (CONVERT(INT, RAND() * 27)) + 1))))

	INSERT INTO NOTA_FISCAL (ID_CLIENTE, ID_VENDEDOR, ID_FORMA, DATA) VALUES 
	(@ID_CLIENTE, @ID_VENDEDOR, @ID_FORMA_PAGAMENTO, @DATA)

END
GO 8400

--PREENCHENDO A TABELA NOTAS FISCAIS REFERENTE A 2017
DECLARE
	@ID_CLIENTE INT,
	@ID_VENDEDOR INT,	
	@ID_FORMA_PAGAMENTO INT,
	@DATA DATE
BEGIN
	SET @ID_CLIENTE = (SELECT TOP 1 IDCLIENTE FROM CLIENTE ORDER BY NEWID())

	SET @ID_VENDEDOR = (SELECT TOP 1 IDVENDEDOR FROM VENDEDOR ORDER BY NEWID())

	SET @ID_FORMA_PAGAMENTO = (SELECT TOP 1 IDFORMA FROM FORMA_PAGAMENTO ORDER BY NEWID())

	SET @DATA = (SELECT
				CONVERT(DATE, CONVERT(VARCHAR(15),'2017-' + 
				CONVERT(VARCHAR(5), (CONVERT(INT, RAND() * 12)) + 1) + '-' + 
				CONVERT(VARCHAR(5), (CONVERT(INT, RAND() * 27)) + 1))))

	INSERT INTO NOTA_FISCAL (ID_CLIENTE, ID_VENDEDOR, ID_FORMA, DATA) VALUES 
	(@ID_CLIENTE, @ID_VENDEDOR, @ID_FORMA_PAGAMENTO, @DATA)

END
GO 9000