CREATE DATABASE COMERCIO_STAGE
GO

USE COMERCIO_STAGE
GO

-- OQ TRAREMOS? 
/* QUAIS DIMENSÕES ? elas são o por. "verei o total vendido POR vendedor (dimensão)", "verei o lucro POR categoria"
 todo por é candidato a ser uma dimensão, oq vem antes do por é um fato. Um fato são as medidas do negocio*/
-- CLIENTE
-- VENDEDOR
-- CATEGORIA
-- FORNECEDOR
-- PRODUTO
-- FORMA DE PAGAMENTO
 
 -- FATOS
 -- total
 -- quantidade
 -- lucro
 -- CUSTO

 -- CRIANDO O AMBIENTE DE STAGE
 CREATE TABLE ST_CLIENTE(
	IDCLIENTE INT DEFAULT NULL,
	NOME VARCHAR(100) DEFAULT NULL,
	SEXO VARCHAR(20) DEFAULT NULL,
	NASCIMENTO DATE DEFAULT NULL,
	CIDADE VARCHAR(100) DEFAULT NULL,
	ESTADO VARCHAR(10) DEFAULT NULL,
	REGIAO VARCHAR(20) DEFAULT NULL 
 )
 GO

 -- COLANDO O EMAIL NA TABELA, PRA FAZER MALA DIRETA
 USE COMERCIO_STAGE
 GO

 ALTER TABLE ST_CLIENTE
 ADD EMAIL VARCHAR(100)
 GO

 CREATE TABLE ST_VENDEDOR(
	IDVENDEDOR INT DEFAULT NULL,
	NOME VARCHAR(40) DEFAULT NULL,
	SEXO VARCHAR(20) DEFAULT NULL,
	IDGERENTE INT DEFAULT NULL
 )
 GO

 CREATE TABLE ST_CATEGORIA(
	IDCATEGORIA INT DEFAULT NULL,
	NOME VARCHAR(50) DEFAULT NULL 
 )
 GO

 CREATE TABLE ST_FORNECEDOR(
	IDFORNECEDOR INT DEFAULT NULL,
	NOME VARCHAR(100) DEFAULT NULL 
 )
 GO

 CREATE TABLE ST_PRODUTO(
	IDPRODUTO INT DEFAULT NULL,
	NOME VARCHAR(50) DEFAULT NULL,
	VALOR_UNITARIO NUMERIC(10,2) DEFAULT NULL,
	CUSTO_MEDIO NUMERIC(10,2) DEFAULT NULL,
	ID_CATEGORIA INT DEFAULT NULL 
 )
 GO

 CREATE TABLE ST_NOTA(
	IDNOTA INT DEFAULT NULL
 )
 GO

 CREATE TABLE ST_FORMA(
	IDFORMA INT DEFAULT NULL,
	NOME VARCHAR(50) DEFAULT NULL 
 )
 GO

 CREATE TABLE ST_FATO(
	IDCLIENTE INT DEFAULT NULL,
	IDVENDEDOR INT DEFAULT NULL,
	IDPRODUTO INT DEFAULT NULL,
	IDFORNECEDOR INT DEFAULT NULL,
	IDNOTA INT DEFAULT NULL,
	IDFORMA INT DEFAULT NULL,
	QUANTIDADE INT DEFAULT NULL,
	TOTAL_ITEM NUMERIC(10,2) DEFAULT NULL,
	DATA DATE DEFAULT NULL,
	CUSTO_TOTAL NUMERIC(10,2) DEFAULT NULL,
	LUCRO_TOTAL NUMERIC(10,2) DEFAULT NULL 
 )
 GO

 --CRIANDO DATABASE PARA ARMAZENAR ERROS VINDOS DO INTEGRATION SERVICES
 CREATE DATABASE BI_ERROR
 GO