		------------------------
		---CONEXAO COM O DW-----
		------------------------

		USE COMERCIO_DW
		GO

		------------------------
		--CRIAÇAO DA PROCEDURE--
		------------------------

		CREATE PROC CARGA_FATO
		AS

		DECLARE @FINAL DATETIME 
		DECLARE	@INICIAL DATETIME
		
		--PEGANDO A MAIOR DATA DA DIMENSAO TEMPO
		SELECT  @FINAL = MAX(DATA)
		FROM COMERCIO_DW.DBO.DIM_TEMPO T

		--PEGANDO A MAIOR DATA DA TABELA FATO, DANDO UM JOIN POR CAUSA DA IDSK
		-- ELA VAI SER NULA NA 1ª EXECUÇÃO PQ A TABELA TA VAZIA
		SELECT @INICIAL = MAX(DATA)
			FROM COMERCIO_DW.DBO.FATO FT
			JOIN COMERCIO_DW.DBO.DIM_TEMPO T ON (FT.IDTEMPO=T.IDSK)
		
		-- CAIRA CASO ESTEJA VAZIA
		-- E COLOCARA A MENOR DATA QUE ESTIVER NA DIM TEMPO
		IF @INICIAL IS NULL
		BEGIN
			SELECT @INICIAL = MIN(DATA)
			FROM COMERCIO_DW.DBO.DIM_TEMPO T
		END

		--FAZENDO AS CARGAS
		INSERT INTO COMERCIO_DW.DBO.FATO(
			IDNOTA ,
			IDCLIENTE ,
			IDVENDEDOR ,
			IDFORMA ,
			IDFORNECEDOR,
			IDPRODUTO,
			IDTEMPO,
			QUANTIDADE,
			TOTALITEM,
			CUSTOTOTAL,
			LUCROTOTAL )
		SELECT
			N.IDSK AS IDNOTA,
			C.IDSK AS IDCLIENTE,
			V.IDSK AS IDVENDEDOR,
		   FO.IDSK AS IDFORMA,
		   FN.IDSK AS IDFORNECEDOR,
			P.IDSK AS IDPRODUTO,	
			T.IDSK as IDTEMPO,
			F.QUANTIDADE,
			F.TOTAL_ITEM,
			F.CUSTO_TOTAL,
			F.LUCRO_TOTAL
	
		FROM
			COMERCIO_STAGE.DBO.ST_FATO F
			-- FAZENDO JOINS COM AS DIMENSOES DO DW
			-- JOIN DA FATO COM A DIMENSAO
			-- ELA NAO TEM SCD, DAI SÓ TRAZ O ID MESMO, PQ NAO TEM VALIDADE
			INNER JOIN DBO.DIM_FORMA FO
			on (F.IDFORMA=FO.IDFORMA)	 

			INNER JOIN DBO.DIM_NOTA N
			on (F.IDNOTA=N.IDNOTA)

			/*  ESTA TRAZENDO OS IDS PARA A TABELA FATO
				ESTAMOS TRAZENDO O PRODUTO CORRETO (PQ PODEMOS TER MESMOS ID PRA PRODUTOS SÓ QUE UM FOI DESCONTINUADO),
				QUE ESTEJA EM ABERTO, POR ISSO VERIFICAMOS:
				 - SE A DATA DE INICIO DELE É MENOR QUE A DATA DO FATO E 
				 - SE ELE ESTÁ ABERTO OU SE ELE FOI FECHADO SÓ DEPOIS DO FATO, POR TANTO ESTARIA ABERTO NO MOMENTO DAQUELE FATO
			*/
			INNER JOIN DBO.DIM_FORNECEDOR FN
			on (F.IDFORNECEDOR=FN.IDFORNECEDOR
				AND (FN.INICIO <= F.DATA AND (FN.FIM >= F.DATA) or (FN.FIM IS NULL)))

			INNER JOIN DBO.DIM_CLIENTE C
			on (F.IDCLIENTE=C.IDCLIENTE
				AND (C.INICIO <= F.DATA
				AND (C.FIM >= F.DATA) or (C.FIM IS NULL)))

				INNER JOIN DBO.DIM_VENDEDOR V
			on (F.IDVENDEDOR=V.IDVENDEDOR
				AND (V.INICIO <= F.DATA
				AND (V.FIM >= F.DATA) or (V.FIM IS NULL)))

				INNER JOIN DBO.DIM_PRODUTO P
			ON (F.IDPRODUTO=P.IDPRODUTO 
			AND (P.INICIO <= F.DATA 
			AND (P.FIM >= F.DATA) OR (P.FIM IS NULL)))

			-- MESMA COISA DOS DE CIMA, POREM MUDANDO O FORMATO DA DATA PARA O FORMATO BR
			INNER JOIN DBO.DIM_TEMPO T
			ON (CONVERT(VARCHAR, T.DATA,102) = CONVERT(VARCHAR,
			F.DATA,102))
			--WHERE F.DATA > @INICIAL AND F.DATA < @FINAL
			WHERE F.DATA BETWEEN @INICIAL AND @FINAL
GO
