USE [COMERCIO_DW]
GO

CREATE VIEW V_ANALISE_FORNECEDOR AS
SELECT FN.NOME AS FORNECEDOR,
		T.ANO AS ANO,
		SUM(F.QUANTIDADE) AS QUANTIDADE,
		SUM(F.TOTAL_ITEM) AS TOTAL_VENDIDO
FROM COMERCIO_STAGE.DBO.ST_FATO F

INNER JOIN DBO.DIM_FORNECEDOR FN
ON F.IDFORNECEDOR = FN.IDFORNECEDOR

INNER JOIN DBO.DIM_TEMPO T
ON (CONVERT(VARCHAR, T.DATA, 102)) = 
	(CONVERT(VARCHAR, F.DATA, 102))

GROUP BY FN.NOME, T.ANO
GO


-- SELECIONANDO OS PRODUTOS PARA O RELATORIO LINKADO A UM OUTRO RELATORIO
SELECT DISTINCT P.NOME AS PRODUTO,
C.NOME AS CATEGORIA
FROM DIM_PRODUTO P
INNER JOIN FATO FA
ON P.IDSK = FA.IDPRODUTO
INNER JOIN DIM_FORNECEDOR F
ON F.IDSK = FA.IDFORNECEDOR
INNER JOIN CATEGORIA C
ON IDCATEGORIA = ID_CATEGORIA
WHERE F.NOME = @FORNECEDOR