use COMERCIO_DW
go

SELECT REGIAO, ANO,
	SUM(LUCROTOTAL) AS LUCRO,
	SUM(QUANTIDADE) AS QUANTIDADE,
	SUM(TOTALITEM) AS TOTAL_ITEM,
	SUM(CUSTOTOTAL) AS CUSTO_TOTAL
FROM DIM_CLIENTE
INNER JOIN FATO F
ON IDSK = F.IDCLIENTE
INNER JOIN DIM_TEMPO T
ON F.IDTEMPO = T.IDSK
GROUP BY REGIAO, ANO
ORDER BY 1, 2
GO
